#!/system/bin/sh
#

insmod /system/lib/modules/bluetooth.ko
insmod /system/lib/modules/rfcomm.ko
insmod /system/lib/modules/bnep.ko
insmod /system/lib/modules/bfusb.ko
insmod /system/lib/modules/btusb.ko
insmod /system/lib/modules/hci_uart.ko
insmod /system/lib/modules/ath3k.ko
insmod /system/lib/modules/bcm203x.ko
insmod /system/lib/modules/bpa10x.ko

echo "done Bluetooth Modules Autoload"
