#!/system/bin/sh
#

insmod /system/lib/modules/usbnet.ko
insmod /system/lib/modules/asix.ko
insmod /system/lib/modules/mcs7830.ko
insmod /system/lib/modules/qf9700.ko
insmod /system/lib/modules/rtl8150.ko

echo "done USBNet Modules Autoload"
